export const BRAND = {
  name: 'Sheikh Mohammed Zabuur',
  shortName: 'Sheikh Mohammed Zabuur',
  tagline: 'Authentic Islamic Lessons — Learn Directly From Sheikh Mohammed Zabuur',
  description: 'Dedicated to teaching authentic Islamic sciences through daily lessons, structured study circles, audio lectures, video lessons, live broadcasts, and educational resources.',
  logo: '/logo.svg',
  logoIcon: '/favicon.svg',
  email: 'info@sheikhmohammedzabuur.com',
  social: {
    facebook: 'https://facebook.com/profile.php?id=61555767907866',
    youtube: 'https://youtube.com/@sheikhmahammadzabuur-b7f',
    tiktok: 'https://www.tiktok.com/@sheikh.mahammad.z',
    telegram: 'https://t.me/Sheikh_Mohammed_Zabuur',
    twitter: '#',
    instagram: 'https://instagram.com/sheikhmohammedzabuur',
  },
  sheikh: {
    name: 'Sheikh Mohammed Zabuur',
    title: 'Scholar & Islamic Educator',
    languages: ['Afaan Oromo', 'Arabic', 'English'],
    specialties: ['Tafsir', 'Hadith', 'Aqeedah', 'Fiqh', 'Tajweed', 'Seerah', 'Arabic'],
  },
  colors: {
    primary: '#0D6B3D',
    primaryDark: '#084C2A',
    primaryLight: '#1B8D52',
    gold: '#D4AF37',
    goldDark: '#B8960F',
    goldLight: '#FCD34D',
    darkBg: '#0A0F0C',
    darkCard: '#111815',
    lightBg: '#F8FAFC',
  },
  stats: {
    yearsTeaching: '10+',
    dailySeries: '7',
    studentsBenefiting: '1000+',
    access: '24/7',
  },
} as const;
