export const BRAND = {
  name: 'Sheikh Mohammed Zabuur',
  shortName: 'Sheikh Mohammed Zabuur',
  tagline: 'Authentic Islamic Knowledge Through Audio Lectures, Video Lessons, PDFs, and Live Sessions',
  description: 'A dedicated Islamic media platform offering authentic audio lectures, video classes, PDF books, and live streams by Sheikh Mohammed Zabuur.',
  logo: '/logo.svg',
  logoIcon: '/favicon.svg',
  email: 'info@sheikhmohammedzabuur.com',
  social: {
    facebook: 'https://facebook.com/profile.php?id=61555767907866',
    youtube: 'https://youtube.com/@sheikhmahammadzabuur-b7f',
    tiktok: 'https://www.tiktok.com/@sheikh.mahammad.z',
    telegram: 'https://t.me/Sheikh_Mohammed_Zabuur',
    twitter: '#',
    instagram: 'https://instagram.com/sheikhmohammedzabuur',
  },
  sheikh: {
    name: 'Sheikh Mohammed Zabuur',
    title: 'Scholar & Islamic Educator',
    languages: ['Afaan Oromo', 'Arabic', 'English'],
    specialties: ['Aqeedah', 'Tafsir', 'Hadith', 'Fiqh', 'Seerah', 'Arabic', 'Tajweed'],
  },
  colors: {
    primary: '#0EA5E9',
    primaryDark: '#0369A1',
    primaryLight: '#38BDF8',
    gold: '#F59E0B',
    goldDark: '#D97706',
    goldLight: '#FCD34D',
    teal: '#14B8A6',
    darkBg: '#020617',
    darkCard: '#0F172A',
    lightBg: '#F8FAFC',
  },
  stats: {
    audioLectures: '100+',
    videoLectures: '50+',
    pdfs: '30+',
    languages: '4',
  },
} as const;
